# Generated by Django 5.1.6 on 2025-04-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_category_language_alter_location_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="zip_code",
            new_name="zipCode",
        ),
    ]
