# Generated by Django 5.1.6 on 2025-04-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_rename_zip_code_location_zipcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user", "is_default"),
                name="unique_default_per_user",
            ),
        ),
    ]
