name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        coverage run manage.py test
        coverage report
        coverage xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Railway
      run: npm install -g @railway/cli
    
    - name: Deploy to Railway and Update Description
      run: |
        DEPLOY_URL=$(railway up --service ${{ github.event.repository.name }} | grep -o 'https://.*\.railway\.app')
        echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
        
        # Update repository description with deployment URL
        curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }} \
          -d "{\"description\":\"Deployment URL: $DEPLOY_URL\"}"
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Update deployment status
      run: |
        echo "Deployment successful! 🚀"
        echo "Your app is live at: ${{ env.DEPLOY_URL }}"
